"""Calculation methodology payload for audit/report transparency pages."""

from __future__ import annotations

from datetime import date


def _metric(
    metric_id,
    name,
    formula,
    code_formula,
    variables,
    interpretation,
    edge_cases,
    units,
    source_refs,
):
    return {
        "id": metric_id,
        "name": name,
        "formula": formula,
        "code_formula": code_formula,
        "variables": variables,
        "interpretation": interpretation,
        "edge_cases": edge_cases,
        "units": units,
        "source_refs": source_refs,
    }


def build_methodology_payload():
    sections = [
        {
            "id": "numerical-guardrails",
            "title": "Numerical Guardrails & Date Logic",
            "summary": "Shared helper behavior used throughout the metrics engine.",
            "items": [
                _metric(
                    "metric-safe-divide",
                    "Safe Divide",
                    "Numerator / Denominator (guarded)",
                    "safe_divide(numerator, denominator, default=None)",
                    ["Numerator", "Denominator", "Default"],
                    "Performs division only when values are valid and denominator is non-zero.",
                    ["Returns default for None inputs, zero denominator, NaN, Inf, and numeric errors"],
                    "inherits numerator/denominator units",
                    ["services/metrics/common.py::safe_divide"],
                ),
                _metric(
                    "metric-safe-power",
                    "Safe Power",
                    "Base ^ Exponent (guarded)",
                    "safe_power(base, exponent, default=None)",
                    ["Base", "Exponent", "Default"],
                    "Evaluates exponentiation while suppressing invalid numeric outputs.",
                    ["Returns default for None inputs, invalid roots/powers, NaN, Inf, overflow"],
                    "depends on base/exponent",
                    ["services/metrics/common.py::safe_power"],
                ),
                _metric(
                    "metric-safe-log",
                    "Safe Natural Log",
                    "ln(Value) when Value > 0",
                    "safe_log(value, default=None)",
                    ["Value", "Default"],
                    "Computes log only in mathematically valid positive domain.",
                    ["Returns default for None, non-positive input, NaN, Inf, overflow"],
                    "log points",
                    ["services/metrics/common.py::safe_log"],
                ),
                _metric(
                    "metric-effective-exit-date",
                    "Effective Exit Date",
                    "Exit Date if present, else As-Of Date, else Today",
                    "effective_exit_date(deal, as_of_date=None)",
                    ["deal.exit_date", "as_of_date", "system date"],
                    "Defines the end date used for hold-period and implied IRR calculations.",
                    ["Unrealized deals use as_of_date/today when exit date is missing"],
                    "date",
                    ["services/metrics/common.py::effective_exit_date"],
                ),
                _metric(
                    "metric-hold-years",
                    "Hold Period (Years)",
                    "(Effective Exit Date - Investment Date).days / 365.25",
                    "deal_hold_years(deal, as_of_date=None)",
                    ["Investment Date", "Effective Exit Date"],
                    "Converts elapsed calendar days into fractional years for annualized return metrics.",
                    ["Returns None when investment date is missing or elapsed days <= 0"],
                    "years",
                    ["services/metrics/common.py::deal_hold_years"],
                ),
            ],
        },
        {
            "id": "core-returns",
            "title": "Core Returns & Profitability",
            "summary": "Deal-level return identity used by portfolio, track record, and memo outputs.",
            "items": [
                _metric(
                    "metric-total-value",
                    "Total Value",
                    "Realized Value + Unrealized Value",
                    "value_total = realized + unrealized",
                    ["Realized Value", "Unrealized Value"],
                    "Combines distributed and remaining value into total equity value attributed to the deal.",
                    ["Missing realized/unrealized inputs are treated as 0 in deal metrics"],
                    "$M",
                    ["services/metrics/deal.py::compute_deal_metrics"],
                ),
                _metric(
                    "metric-total-value-created",
                    "Total Value Created ($)",
                    "(Realized Value + Unrealized Value) - Equity Invested",
                    "value_created = value_total - equity",
                    ["Total Value", "Equity Invested"],
                    "Measures dollar gain or loss relative to invested equity capital.",
                    ["Negative values indicate value destruction"],
                    "$M",
                    ["services/metrics/deal.py::compute_deal_metrics"],
                ),
                _metric(
                    "metric-gross-moic",
                    "Gross MOIC",
                    "(Realized Value + Unrealized Value) / Equity Invested",
                    "safe_divide(value_total, equity)",
                    ["Realized Value", "Unrealized Value", "Equity Invested"],
                    "Measures total gross value multiple on invested equity.",
                    ["Returns None when invested equity is missing, zero, or invalid"],
                    "multiple (x)",
                    ["services/metrics/deal.py::compute_deal_metrics"],
                ),
                _metric(
                    "metric-realized-moic",
                    "Realized MOIC",
                    "Realized Value / Equity Invested",
                    "safe_divide(realized, equity)",
                    ["Realized Value", "Equity Invested"],
                    "Shows the realized-only multiple of invested capital.",
                    ["Returns None when invested equity is missing, zero, or invalid"],
                    "multiple (x)",
                    ["services/metrics/deal.py::compute_deal_metrics"],
                ),
                _metric(
                    "metric-unrealized-moic",
                    "Unrealized MOIC",
                    "Unrealized Value / Equity Invested",
                    "safe_divide(unrealized, equity)",
                    ["Unrealized Value", "Equity Invested"],
                    "Shows the unrealized mark multiple relative to invested capital.",
                    ["Returns None when invested equity is missing, zero, or invalid"],
                    "multiple (x)",
                    ["services/metrics/deal.py::compute_deal_metrics"],
                ),
                _metric(
                    "metric-implied-irr",
                    "Implied IRR",
                    "(Gross MOIC ^ (1 / Hold Years)) - 1",
                    "_implied_irr(moic, hold_years) with safe_power",
                    ["Gross MOIC", "Hold Years"],
                    "Converts total multiple and hold period into an annualized geometric return.",
                    ["Returns None when MOIC <= 0, hold <= 0, or exponentiation is invalid"],
                    "decimal rate",
                    [
                        "services/metrics/deal.py::_implied_irr",
                        "services/metrics/deal.py::compute_deal_metrics",
                    ],
                ),
            ],
        },
        {
            "id": "operating-metrics",
            "title": "Operating, Leverage, and Growth Metrics",
            "summary": "Entry/exit ratios and growth rates used in dashboard, IC memo, and analysis pages.",
            "items": [
                _metric(
                    "metric-tev-ebitda",
                    "TEV / EBITDA",
                    "Total Enterprise Value / EBITDA",
                    "safe_divide(enterprise_value, ebitda)",
                    ["Enterprise Value", "EBITDA"],
                    "Measures valuation multiple on operating earnings.",
                    ["Returns None when input is missing/invalid, denominator is zero, or computed multiple is negative"],
                    "multiple (x)",
                    ["services/metrics/deal.py::compute_deal_metrics"],
                ),
                _metric(
                    "metric-tev-revenue",
                    "TEV / Revenue",
                    "Total Enterprise Value / Revenue",
                    "safe_divide(enterprise_value, revenue)",
                    ["Enterprise Value", "Revenue"],
                    "Measures valuation multiple on top-line revenue.",
                    ["Returns None when input is missing/invalid or denominator is zero"],
                    "multiple (x)",
                    ["services/metrics/deal.py::compute_deal_metrics"],
                ),
                _metric(
                    "metric-net-debt-ebitda",
                    "Net Debt / EBITDA",
                    "Net Debt / EBITDA",
                    "safe_divide(net_debt, ebitda)",
                    ["Net Debt", "EBITDA"],
                    "Measures leverage relative to earnings power.",
                    ["Returns None when EBITDA is zero/missing/invalid"],
                    "multiple (x)",
                    ["services/metrics/deal.py::compute_deal_metrics"],
                ),
                _metric(
                    "metric-net-debt-tev",
                    "Net Debt / TEV",
                    "Net Debt / Total Enterprise Value",
                    "safe_divide(net_debt, enterprise_value)",
                    ["Net Debt", "Enterprise Value"],
                    "Measures leverage as a share of total enterprise value.",
                    ["Returns None when enterprise value is zero/missing/invalid"],
                    "decimal share",
                    ["services/metrics/deal.py::compute_deal_metrics"],
                ),
                _metric(
                    "metric-ebitda-margin",
                    "EBITDA Margin",
                    "EBITDA / Revenue",
                    "safe_divide(ebitda, revenue) then * 100",
                    ["EBITDA", "Revenue"],
                    "Shows operating profitability intensity at entry and exit.",
                    ["Stored and displayed in percentage points in metrics layer"],
                    "percentage points",
                    ["services/metrics/deal.py::compute_deal_metrics"],
                ),
                _metric(
                    "metric-growth-pct",
                    "Revenue/EBITDA Growth (%)",
                    "((Exit Value - Entry Value) / Entry Value) * 100",
                    "_growth_pct(exit_value, entry_value)",
                    ["Entry Value", "Exit Value"],
                    "Measures total percent growth from entry to exit.",
                    ["Returns None when entry value is zero/missing/invalid"],
                    "percent",
                    ["services/metrics/deal.py::_growth_pct"],
                ),
                _metric(
                    "metric-cagr",
                    "Revenue/EBITDA CAGR (%)",
                    "((Exit Value / Entry Value) ^ (1 / Hold Years) - 1) * 100",
                    "_cagr_pct(exit_value, entry_value, hold_years)",
                    ["Entry Value", "Exit Value", "Hold Years"],
                    "Measures annualized compounded growth over the hold period.",
                    ["Returns None when entry/exit <= 0, hold <= 0, or invalid power"],
                    "percent",
                    ["services/metrics/deal.py::_cagr_pct"],
                ),
            ],
        },
        {
            "id": "aggregation-methodology",
            "title": "Aggregation Methodology",
            "summary": "How deal-level metrics are rolled up into portfolio/fund/page aggregates.",
            "items": [
                _metric(
                    "metric-simple-average",
                    "Simple Average",
                    "sum(metric_i) / count(valid metric_i)",
                    "_avg(values)",
                    ["Valid metric values"],
                    "Arithmetic mean over available, non-null metric values.",
                    ["Returns None when no valid values"],
                    "same units as metric",
                    ["services/metrics/portfolio.py::_avg"],
                ),
                _metric(
                    "metric-equity-weighted-average",
                    "Equity-Weighted Average",
                    "sum(metric_i * equity_i) / sum(equity_i)",
                    "_wavg(pairs) / _metric_aggregate(...) / _weighted_avg(...)",
                    ["Metric_i", "Equity_i"],
                    "Weights each deal by invested equity to reflect capital exposure.",
                    [
                        "Only includes rows with non-null metric and positive weight",
                        "Returns None when weighted denominator <= 0",
                    ],
                    "same units as metric",
                    [
                        "services/metrics/portfolio.py::_wavg",
                        "services/metrics/portfolio.py::_metric_aggregate",
                        "services/metrics/analysis.py::_weighted_avg",
                    ],
                ),
                _metric(
                    "metric-weighted-fallback",
                    "Weighted Fallback Rule",
                    "If no valid weighted pairs, use simple average",
                    "{""wavg"": _wavg(weighted) if weighted else _avg(vals)}",
                    ["Weighted pair set", "Simple-average set"],
                    "Preserves a usable aggregate when weighting is impossible due to missing/invalid equity.",
                    ["Fallback applies only when weighted set is empty"],
                    "same units as metric",
                    ["services/metrics/portfolio.py::_metric_aggregate"],
                ),
            ],
        },
        {
            "id": "loss-analysis",
            "title": "Loss Analysis & Distribution",
            "summary": "Principal-loss diagnostics used in dashboard and IC memo risk blocks.",
            "items": [
                _metric(
                    "metric-loss-ratio-count",
                    "Count-Based Loss Ratio (%)",
                    "(Deals with MOIC < 1.0x / Deals with valid MOIC) * 100",
                    "len(losses) / len(deals_with_moic) * 100",
                    ["Loss deal count", "Valid MOIC deal count"],
                    "Measures the share of evaluated deals that lost principal.",
                    ["Universe excludes deals without positive equity or valid MOIC"],
                    "percent",
                    ["services/metrics/risk.py::compute_loss_and_distribution"],
                ),
                _metric(
                    "metric-loss-ratio-capital",
                    "Capital-Based Loss Ratio (%)",
                    "(Equity invested in deals with MOIC < 1.0x / Total evaluated equity) * 100",
                    "safe_divide(loss_eq, total_eq) * 100",
                    ["Loss equity", "Total evaluated equity"],
                    "Measures how much invested capital was allocated to principal-loss deals.",
                    ["Returns None when total evaluated equity is missing/zero/invalid"],
                    "percent",
                    ["services/metrics/risk.py::compute_loss_and_distribution"],
                ),
                _metric(
                    "metric-moic-buckets",
                    "MOIC Distribution Buckets",
                    "Counts over fixed intervals: [<0.5x, 0.5-1.0x, 1.0-1.5x, 1.5-2.0x, 2.0-3.0x, 3.0x+]",
                    "bucket loop in compute_loss_and_distribution",
                    ["Deal MOIC"],
                    "Shows return dispersion across standardized MOIC ranges.",
                    ["Bucket percentage = bucket count / deals with valid MOIC * 100"],
                    "count and percent",
                    ["services/metrics/risk.py::compute_loss_and_distribution"],
                ),
            ],
        },
        {
            "id": "additive-bridge",
            "title": "Value Creation Bridge (Additive Decomposition)",
            "summary": "Primary value-creation attribution model used at deal, portfolio, and IC memo levels.",
            "items": [
                _metric(
                    "metric-bridge-variables",
                    "Bridge Variable Definitions",
                    "m0 = Entry EBITDA / Entry Revenue; m1 = Exit EBITDA / Exit Revenue; x0 = Entry TEV / Entry EBITDA; x1 = Exit TEV / Exit EBITDA",
                    "m0 = e0 / r0; m1 = e1 / r1; x0 = ev0 / e0; x1 = ev1 / e1",
                    ["r0", "r1", "e0", "e1", "ev0", "ev1"],
                    "Defines the operating and valuation bases used for additive decomposition.",
                    [
                        "When entry/exit EBITDA <= 0 with valid revenue, bridge switches to revenue-multiple fallback using rm0=ev0/r0 and rm1=ev1/r1",
                        "When both entry and exit revenue are missing/near-zero, bridge switches to EBITDA-multiple fallback with explicit EBITDA Growth lever",
                    ],
                    "ratios and multiples",
                    ["services/metrics/bridge.py::compute_additive_bridge"],
                ),
                _metric(
                    "metric-bridge-revenue",
                    "Revenue Growth Impact ($)",
                    "(Exit Revenue - Entry Revenue) * m0 * x0",
                    "(r1 - r0) * m0 * x0",
                    ["Exit Revenue", "Entry Revenue", "Entry Margin m0", "Entry Multiple x0"],
                    "Isolates value change from topline growth while holding margin and multiple at entry levels.",
                    ["Computed at company level then ownership-scaled for fund basis"],
                    "$M",
                    ["services/metrics/bridge.py::compute_additive_bridge"],
                ),
                _metric(
                    "metric-bridge-margin",
                    "Margin Expansion Impact ($)",
                    "Exit Revenue * (m1 - m0) * x0",
                    "r1 * (m1 - m0) * x0",
                    ["Exit Revenue", "Exit/Entry Margin", "Entry Multiple x0"],
                    "Captures value change from EBITDA-margin movement at exit scale.",
                    ["Computed at company level then ownership-scaled for fund basis"],
                    "$M",
                    ["services/metrics/bridge.py::compute_additive_bridge"],
                ),
                _metric(
                    "metric-bridge-multiple",
                    "Multiple Expansion Impact ($)",
                    "(x1 - x0) * Exit EBITDA",
                    "(x1 - x0) * e1",
                    ["Exit Multiple", "Entry Multiple", "Exit EBITDA"],
                    "Captures value change from valuation-multiple rerating.",
                    ["Computed at company level then ownership-scaled for fund basis"],
                    "$M",
                    ["services/metrics/bridge.py::compute_additive_bridge"],
                ),
                _metric(
                    "metric-bridge-fallback-negative-ebitda",
                    "Negative EBITDA Fallback Method ($)",
                    "If Entry EBITDA <= 0 or Exit EBITDA <= 0: Revenue = (r1 - r0) * rm0; Margin = 0; Multiple = (rm1 - rm0) * r1; Leverage = nd0 - nd1",
                    "rm0 = ev0 / r0; rm1 = ev1 / r1; fallback company drivers when e0 <= 0 or e1 <= 0",
                    ["r0", "r1", "ev0", "ev1", "nd0", "nd1"],
                    "Keeps bridge attribution available for negative-EBITDA cases by using revenue-multiple decomposition.",
                    ["Requires non-near-zero revenues and complete EV/revenue/debt inputs"],
                    "$M",
                    ["services/metrics/bridge.py::compute_additive_bridge"],
                ),
                _metric(
                    "metric-bridge-fallback-missing-revenue",
                    "Missing Revenue Fallback Method ($)",
                    "If Entry Revenue and Exit Revenue are missing/near-zero: EBITDA Growth = (e1 - e0) * x0; Multiple = (x1 - x0) * e1; Leverage = nd0 - nd1",
                    "x0 = ev0 / e0; x1 = ev1 / e1; fallback company drivers when r0 and r1 are missing/near-zero",
                    ["e0", "e1", "ev0", "ev1", "nd0", "nd1"],
                    "Keeps bridge attribution available without revenue history by using EBITDA growth plus multiple and leverage decomposition.",
                    [
                        "Requires valid non-near-zero EBITDA and EV/debt inputs",
                        "Display rows hide Margin for this fallback and show explicit EBITDA Growth lever",
                        "Legacy payload compatibility aliases EBITDA Growth into revenue with margin fixed at 0",
                    ],
                    "$M",
                    ["services/metrics/bridge.py::compute_additive_bridge"],
                ),
                _metric(
                    "metric-bridge-leverage",
                    "Leverage Impact ($)",
                    "Entry Net Debt - Exit Net Debt",
                    "nd0 - nd1",
                    ["Entry Net Debt", "Exit Net Debt"],
                    "Measures value creation from debt paydown (or loss from leverage increase).",
                    ["Computed at company level then ownership-scaled for fund basis"],
                    "$M",
                    ["services/metrics/bridge.py::compute_additive_bridge"],
                ),
                _metric(
                    "metric-bridge-ownership",
                    "Ownership Scaling Methodology",
                    "Use explicit ownership_pct when provided; else Equity Invested / (Entry TEV - Entry Net Debt)",
                    "_derive_ownership(deal, warnings)",
                    ["ownership_pct", "Equity Invested", "Entry TEV", "Entry Net Debt"],
                    "Converts company-level bridge drivers to fund pro-rata contribution.",
                    [
                        "If entry equity <= 0, fallback ownership is 100% with warning",
                        "If ownership cannot be derived, bridge is not ready",
                    ],
                    "decimal share",
                    ["services/metrics/bridge.py::_derive_ownership"],
                ),
                _metric(
                    "metric-bridge-residual",
                    "Other / Residual ($)",
                    "Total Value Created - (Revenue + Margin + Multiple + Leverage)",
                    "other = target_value_created - subtotal",
                    ["Total Value Created", "Revenue", "Margin", "Multiple", "Leverage"],
                    "Closure term that reconciles additive driver subtotal to observed value created.",
                    ["Always computed as reconciliation residual"],
                    "$M",
                    ["services/metrics/bridge.py::compute_additive_bridge"],
                ),
                _metric(
                    "metric-bridge-unit-normalization",
                    "Bridge MOIC and % Normalization",
                    "MOIC Contribution = Driver($) / Equity Invested; % of Value Created = Driver($) / Total Value Created",
                    "_normalize_unit(drivers_dollar, unit, equity, value_created)",
                    ["Driver($)", "Equity Invested", "Total Value Created"],
                    "Provides consistent bridge reporting in dollars, MOIC impact, or percent contribution.",
                    [
                        "MOIC normalization returns None when equity <= 0",
                        "Percent normalization returns None when |value_created| < EPS",
                    ],
                    "x or percent",
                    ["services/metrics/bridge.py::_normalize_unit"],
                ),
                _metric(
                    "metric-bridge-diagnostics",
                    "Ownership Sensitivity Diagnostic",
                    "Driver subtotal under +/-10% ownership scaling and residual recompute",
                    "compute_bridge_diagnostics(additive_bridge)",
                    ["Fund driver subtotal", "Fund value created"],
                    "Shows bridge sensitivity to ownership assumptions for non-residual components.",
                    ["Diagnostic only populated when bridge is ready and ownership/value are valid"],
                    "$M",
                    ["services/metrics/bridge.py::compute_bridge_diagnostics"],
                ),
            ],
        },
        {
            "id": "portfolio-rollups",
            "title": "Portfolio, Mix, and Scorecard Rollups",
            "summary": "Cross-deal formulas used for dashboard charts/tables and memo ranking tables.",
            "items": [
                _metric(
                    "metric-portfolio-gross-moic",
                    "Portfolio Gross MOIC",
                    "Portfolio Total Value / Portfolio Total Equity",
                    "safe_divide(total_value, total_equity)",
                    ["Total Value", "Total Equity"],
                    "Fund-level aggregate gross multiple across selected deal universe.",
                    ["Returns None when total equity <= 0"],
                    "multiple (x)",
                    ["services/metrics/portfolio.py::compute_portfolio_analytics"],
                ),
                _metric(
                    "metric-vintage-rollup",
                    "Vintage Rollup Metrics",
                    "Vintage MOIC = Vintage Total Value / Vintage Total Equity",
                    "safe_divide(total_value, total_equity) per year",
                    ["Vintage deal set"],
                    "Summarizes deal counts, equity, value created, and MOIC by investment vintage year.",
                    ["Vintage year uses year_invested or investment_date.year"],
                    "mixed",
                    ["services/metrics/portfolio.py::compute_vintage_series"],
                ),
                _metric(
                    "metric-moic-hold-bubble-radius",
                    "MOIC vs Hold Bubble Radius",
                    "r = 5 + 9 * sqrt(Deal Equity / Max Equity)",
                    "radius = 5 + (9 * math.sqrt(equity / max_equity))",
                    ["Deal Equity", "Max Equity in set"],
                    "Scales bubble area by relative invested equity in the current filter cut.",
                    ["Uses fallback radius 6 when max/row equity not positive"],
                    "pixels",
                    ["services/metrics/portfolio.py::compute_moic_hold_scatter"],
                ),
                _metric(
                    "metric-value-creation-mix-pct",
                    "Value Creation Mix % by Group",
                    "Driver % = Driver($) / Group Total Value Created",
                    "safe_divide(driver_dollar, total_value_created)",
                    ["Group driver dollars", "Group total value created"],
                    "Normalizes value-creation attribution within each fund/sector/exit-type group.",
                    ["Returns None for groups with near-zero total value created"],
                    "percent",
                    ["services/metrics/portfolio.py::compute_value_creation_mix"],
                ),
                _metric(
                    "metric-realized-unrealized-exposure",
                    "Realized/Unrealized Exposure by Fund",
                    "Fund Realized = sum(realized); Fund Unrealized = sum(unrealized)",
                    "grouped sums in compute_realized_unrealized_exposure",
                    ["Fund", "Realized Value", "Unrealized Value"],
                    "Shows value split by realization state at fund level.",
                    ["Missing realized/unrealized values treated as 0"],
                    "$M",
                    ["services/metrics/portfolio.py::compute_realized_unrealized_exposure"],
                ),
                _metric(
                    "metric-loss-concentration-heatmap",
                    "Loss Concentration Matrix",
                    "Cell Value = sum(Equity for deals with MOIC < 1.0x) by Sector x Geography",
                    "matrix[sector][geography] += equity",
                    ["Sector", "Geography", "Deal Equity", "Deal MOIC"],
                    "Identifies where loss capital is concentrated.",
                    ["Includes only deals with positive equity and MOIC < 1.0x"],
                    "$M",
                    ["services/metrics/portfolio.py::compute_loss_concentration_heatmap"],
                ),
                _metric(
                    "metric-exit-type-calculated-moic",
                    "Exit-Type Calculated MOIC",
                    "sum(Total Value) / sum(Equity) per Exit Type",
                    "safe_divide(total_value, total_equity)",
                    ["Exit Type", "Group Total Value", "Group Total Equity"],
                    "Compares realized outcomes by exit route using capital-weighted MOIC.",
                    ["Returns None when grouped total equity <= 0"],
                    "multiple (x)",
                    ["services/metrics/portfolio.py::compute_exit_type_performance"],
                ),
                _metric(
                    "metric-lead-partner-scorecard",
                    "Lead Partner Scorecard",
                    "Weighted MOIC = sum(total value) / sum(capital); Hit Rate = hit_count / valid_moic_count; Loss Ratio = loss_count / valid_moic_count",
                    "compute_lead_partner_scorecard",
                    ["Partner capital", "Partner total value", "MOIC hit/loss counts"],
                    "Ranks execution by partner with return and downside quality indicators.",
                    ["Hit threshold is MOIC >= 2.0x; loss threshold is MOIC < 1.0x"],
                    "x and percent",
                    ["services/metrics/portfolio.py::compute_lead_partner_scorecard"],
                ),
            ],
        },
        {
            "id": "track-record-methodology",
            "title": "Track Record Methodology",
            "summary": "Row and rollup logic powering /track-record and print-ready export.",
            "items": [
                _metric(
                    "metric-track-record-gross-irr-precedence",
                    "Gross IRR Precedence",
                    "Gross IRR = Uploaded IRR from Deals sheet",
                    "gross_irr = deal.irr",
                    ["Uploaded IRR"],
                    "Uses only manually provided Gross IRR for displayed/reporting IRR outputs.",
                    ["If missing/invalid, displays as None/—"],
                    "decimal rate",
                    ["services/metrics/portfolio.py::compute_deal_track_record"],
                ),
                _metric(
                    "metric-track-record-pct-total-invested",
                    "% of Total Invested",
                    "Deal Equity / Fund Total Invested Equity",
                    "safe_divide(row.invested_equity, fund_invested_total)",
                    ["Deal equity", "Fund invested total"],
                    "Shows each deal's capital weight inside its fund section.",
                    ["Returns None when fund invested total <= 0"],
                    "percent",
                    ["services/metrics/portfolio.py::compute_deal_track_record"],
                ),
                _metric(
                    "metric-track-record-pct-fund-size",
                    "% of Fund Size",
                    "Deal Equity / Fund Size",
                    "safe_divide(row.invested_equity, fund_size)",
                    ["Deal equity", "Fund size"],
                    "Shows fund-sizing utilization per deal when fund size is provided.",
                    ["Returns None when fund size is missing/invalid; conflicts flagged separately"],
                    "percent",
                    ["services/metrics/portfolio.py::compute_deal_track_record"],
                ),
                _metric(
                    "metric-track-record-rollup-weighted-fields",
                    "Weighted Rollup Fields",
                    "Weighted Hold/Ownership/IRR = sum(metric * equity) / sum(equity)",
                    "_update_track_totals + _finalize_track_totals",
                    ["Deal hold years", "Ownership", "Gross IRR", "Deal equity"],
                    "Ensures rollup averages reflect capital weighting, not simple deal count.",
                    ["Only includes rows with non-null metric and positive equity"],
                    "years, percent, rate",
                    [
                        "services/metrics/portfolio.py::_update_track_totals",
                        "services/metrics/portfolio.py::_finalize_track_totals",
                    ],
                ),
                _metric(
                    "metric-track-record-rollup-moic",
                    "Rollup Gross/Realized/Unrealized MOIC",
                    "Gross MOIC = Total Value / Invested; Realized MOIC = Realized / Invested; Unrealized MOIC = Unrealized / Invested",
                    "safe_divide(total_value|realized|unrealized, invested_equity)",
                    ["Rollup total value", "Rollup realized", "Rollup unrealized", "Rollup invested equity"],
                    "Separates total return into realized and remaining mark components.",
                    ["Returns None when invested equity <= 0"],
                    "multiple (x)",
                    ["services/metrics/portfolio.py::_finalize_track_totals"],
                ),
                _metric(
                    "metric-track-record-net-conflicts",
                    "Fund Net Metric Conflict Rule",
                    "If repeated net field values differ beyond tolerance, output N/A",
                    "_resolve_scalar(values, tolerance=1e-9)",
                    ["Repeated fund-level net_irr/net_moic/net_dpi values"],
                    "Prevents silent selection when duplicated fund-level fields disagree across deals.",
                    ["Conflicting non-null values set metric to None with conflict flag"],
                    "n/a",
                    [
                        "services/metrics/portfolio.py::_resolve_scalar",
                        "services/metrics/portfolio.py::_fund_net_performance",
                    ],
                ),
            ],
        },
        {
            "id": "analysis-modules",
            "title": "Analysis Page Methodologies",
            "summary": "Formulas powering extended analysis modules beyond the dashboard.",
            "items": [
                _metric(
                    "metric-tvpi",
                    "TVPI",
                    "(Distributed + NAV) / Paid-In",
                    "safe_divide(distributed + nav, paid_in)",
                    ["Distributed capital", "NAV", "Paid-in capital"],
                    "Measures total value returned plus remaining NAV relative to contributed capital.",
                    ["Returns None when paid-in is missing/zero/invalid"],
                    "multiple (x)",
                    ["services/metrics/analysis.py::compute_fund_liquidity_analysis"],
                ),
                _metric(
                    "metric-dpi",
                    "DPI",
                    "Distributed / Paid-In",
                    "safe_divide(distributed, paid_in)",
                    ["Distributed capital", "Paid-in capital"],
                    "Measures realized distributions relative to paid-in capital.",
                    ["Returns None when paid-in is missing/zero/invalid"],
                    "multiple (x)",
                    ["services/metrics/analysis.py::compute_fund_liquidity_analysis"],
                ),
                _metric(
                    "metric-rvpi",
                    "RVPI",
                    "NAV / Paid-In",
                    "safe_divide(nav, paid_in)",
                    ["NAV", "Paid-in capital"],
                    "Measures remaining unrealized value relative to paid-in capital.",
                    ["Returns None when paid-in is missing/zero/invalid"],
                    "multiple (x)",
                    ["services/metrics/analysis.py::compute_fund_liquidity_analysis"],
                ),
                _metric(
                    "metric-pic",
                    "PIC",
                    "Paid-In / Committed",
                    "safe_divide(paid_in, committed)",
                    ["Paid-in capital", "Committed capital"],
                    "Measures investment pacing against committed capital.",
                    ["Returns None when committed is missing/zero/invalid"],
                    "decimal share",
                    ["services/metrics/analysis.py::compute_fund_liquidity_analysis"],
                ),
                _metric(
                    "metric-gross-tvpi",
                    "Gross TVPI",
                    "Quarterly Gross Equity Value / Total Invested Equity",
                    "safe_divide(gross_equity_by_quarter[q], total_invested)",
                    ["Quarterly gross equity", "Total invested equity"],
                    "Compares quarterly gross mark level to invested capital base.",
                    ["Returns None when total invested <= 0"],
                    "multiple (x)",
                    ["services/metrics/analysis.py::compute_fund_liquidity_analysis"],
                ),
                _metric(
                    "metric-underwrite-deltas",
                    "Underwrite Delta Metrics",
                    "Delta = Actual Metric - Underwrite Target",
                    "delta_* fields in compute_underwrite_outcome_analysis",
                    ["Actual IRR/MOIC/Hold/Multiple/CAGR", "Target baseline"],
                    "Measures underwriting accuracy and repeatability by comparing outcomes to baseline plans.",
                    ["Deltas only computed when both actual and target exist"],
                    "mixed",
                    ["services/metrics/analysis.py::compute_underwrite_outcome_analysis"],
                ),
                _metric(
                    "metric-valuation-quality",
                    "Valuation Quality Metrics",
                    "Staleness Days = as_of_date - latest_mark_date; Volatility = avg(abs((q_t - q_t-1)/q_t-1)); Mark Error = (Realized Exit Equity - Last Pre-Exit Fair Value) / Last Pre-Exit Fair Value",
                    "compute_valuation_quality_analysis",
                    ["Quarterly marks", "As-of date", "Realized exit value", "Pre-exit mark"],
                    "Assesses mark freshness, mark stability, and pre-exit fair-value accuracy.",
                    [
                        "Markdown flag when latest mark < peak mark",
                        "Coverage % = deals with latest mark / unrealized deals",
                    ],
                    "days, percent",
                    ["services/metrics/analysis.py::compute_valuation_quality_analysis"],
                ),
                _metric(
                    "metric-exit-readiness",
                    "Exit Readiness Scoring",
                    "Score Ratio = clamp(actual/target, 0, 1); Thesis Score = avg(valid component ratios) * 100",
                    "_score_ratio + compute_exit_readiness_analysis",
                    ["Current MOIC", "Hold years", "EBITDA CAGR", "Underwrite targets"],
                    "Combines performance, timing, and operating progress into an IC-ready thesis completion score.",
                    [
                        "Ready flag when thesis_score >= 75 and timing rule passes",
                        "Time above target uses quarterly mark MOIC checks against target MOIC",
                    ],
                    "score and years",
                    ["services/metrics/analysis.py::compute_exit_readiness_analysis"],
                ),
                _metric(
                    "metric-stress-lab-core",
                    "Stress Lab Deal Revaluation",
                    "Stressed EBITDA = max(0, Current EBITDA * (1 + EBITDA Shock)); Stressed Multiple = max(0.10, Current Multiple + Multiple Shock); Stressed EV = Stressed EBITDA * Stressed Multiple; Stressed Equity = max(0, Stressed EV - Net Debt)",
                    "compute_stress_lab_analysis",
                    ["Current EBITDA", "Current Multiple", "EBITDA shock", "Multiple shock", "Net debt"],
                    "Reprices unrealized exposure under per-deal operating and valuation shock inputs.",
                    [
                        "If both shocks <= 0, stressed unrealized value is capped at current unrealized",
                        "Stressed implied IRR uses expected hold period override when provided",
                    ],
                    "$M, x, rate",
                    ["services/metrics/analysis.py::compute_stress_lab_analysis"],
                ),
                _metric(
                    "metric-stress-lab-rollups",
                    "Stress Rollup Metrics",
                    "Current/Stressed Total MOIC = Current/Stressed Total Value / Total Invested; Fund subtotal MOIC and IRR computed from fund invested and weighted hold assumptions",
                    "summary + fund_subtotals in compute_stress_lab_analysis",
                    ["Portfolio totals", "Fund totals", "Weighted hold periods"],
                    "Aggregates per-deal stress outputs into portfolio and fund subtotal comparisons.",
                    ["IRR rollups use implied IRR from rollup MOIC and weighted hold period"],
                    "multiple (x), rate",
                    ["services/metrics/analysis.py::compute_stress_lab_analysis"],
                ),
                _metric(
                    "metric-deal-trajectory",
                    "Deal Trajectory Metrics",
                    "Implied Multiple = Enterprise Value / EBITDA; cumulative calls/distributions are quarter-wise running sums after event classification",
                    "compute_deal_trajectory_analysis",
                    ["Quarterly EV", "Quarterly EBITDA", "Cashflow events"],
                    "Builds time-series view of operating, valuation, and cashflow path for a selected deal.",
                    [
                        "Cashflow event types classified by keywords; unknown sign-based fallback",
                        "Equity value resolved as explicit equity_value else EV - Net Debt",
                    ],
                    "mixed",
                    ["services/metrics/analysis.py::compute_deal_trajectory_analysis"],
                ),
            ],
        },
        {
            "id": "ic-memo-methodology",
            "title": "IC Memo Grouping & Decile Methodology",
            "summary": "Ranking/slicing logic used to generate memo deciles and execution tables.",
            "items": [
                _metric(
                    "metric-ic-group-weighted-moic",
                    "Group Weighted MOIC",
                    "Group Total Value / Group Invested Equity",
                    "safe_divide(bucket.total_value, bucket.invested_equity)",
                    ["Group total value", "Group invested equity"],
                    "Capital-weighted return basis used for ranking memo dimension groups.",
                    ["Returns None when group invested equity <= 0"],
                    "multiple (x)",
                    ["services/metrics/ic_memo.py::_finalize_group_bucket"],
                ),
                _metric(
                    "metric-ic-group-weighted-irr",
                    "Group Weighted Gross IRR",
                    "sum(Deal Gross IRR * Deal Equity) / sum(Deal Equity)",
                    "safe_divide(_irr_num, _irr_den)",
                    ["Deal gross IRR", "Deal equity"],
                    "Annualized return proxy for group-level memo comparisons.",
                    ["Only includes deals with non-null IRR and positive equity"],
                    "decimal rate",
                    ["services/metrics/ic_memo.py::_update_group_bucket"],
                ),
                _metric(
                    "metric-ic-decile-sizing",
                    "Top/Bottom Decile Size",
                    "n = max(min_count, ceil(group_count * decile_pct))",
                    "pick_deciles(groups, pct, min_count)",
                    ["group_count", "decile_pct", "min_count"],
                    "Applies strict tail selection for top and bottom performance slices.",
                    ["Defaults: decile_pct=0.10, min_count=1"],
                    "count",
                    ["services/metrics/ic_memo.py::pick_deciles"],
                ),
                _metric(
                    "metric-ic-status-rollup",
                    "Status Rollup Normalization",
                    "Fully Realized + Partially Realized -> Realized; Unrealized -> Unrealized; otherwise Other",
                    "normalize_status_rollup(raw_status)",
                    ["Raw deal status"],
                    "Creates consistent status buckets for memo slicing and decile logic.",
                    ["Blank status defaults to Unrealized bucket"],
                    "category",
                    ["services/metrics/ic_memo.py::normalize_status_rollup"],
                ),
            ],
        },
    ]

    glossary = [
        {"term": "MOIC", "definition": "Multiple on Invested Capital."},
        {"term": "IRR", "definition": "Internal Rate of Return (annualized)."},
        {"term": "TVPI", "definition": "Total Value to Paid-In."},
        {"term": "DPI", "definition": "Distributed to Paid-In."},
        {"term": "RVPI", "definition": "Residual Value to Paid-In."},
        {"term": "PIC", "definition": "Paid-In Capital as a share of committed capital."},
        {"term": "EPS", "definition": "Small positive threshold (1e-9) used to avoid unstable division/normalization."},
    ]

    rules = [
        {
            "id": "rule-loss-definition",
            "name": "Loss Deal Definition",
            "rule": "A deal is counted as a loss when MOIC < 1.0x and equity invested is positive.",
            "source_refs": ["services/metrics/risk.py::compute_loss_and_distribution"],
        },
        {
            "id": "rule-bridge-readiness",
            "name": "Bridge Readiness",
            "rule": "Bridge is ready with required EV/debt/equity fields plus method-specific inputs. Uses EBITDA-additive when revenues and EBITDA are valid, revenue-multiple fallback when EBITDA is non-positive, and EBITDA-multiple fallback when both revenues are missing/near-zero.",
            "source_refs": ["services/metrics/bridge.py::compute_additive_bridge"],
        },
        {
            "id": "rule-exit-readiness-threshold",
            "name": "Exit Readiness Threshold",
            "rule": "Deal is readiness-flagged when thesis_score >= 75 and target-hold timing condition is satisfied.",
            "source_refs": ["services/metrics/analysis.py::compute_exit_readiness_analysis"],
        },
        {
            "id": "rule-stress-shock-guardrail",
            "name": "Stress Guardrail",
            "rule": "When both multiple and EBITDA shocks are non-positive, stressed unrealized value cannot exceed current unrealized value.",
            "source_refs": ["services/metrics/analysis.py::compute_stress_lab_analysis"],
        },
    ]

    return {
        "meta": {
            "title": "Calculation Methodology & Audit",
            "as_of": date.today().isoformat(),
            "scope_note": "Backend formulas sourced from services/metrics/* and helpers",
        },
        "sections": sections,
        "glossary": glossary,
        "rules": rules,
    }
