"""baseline schema

Revision ID: 4a62775748c8
Revises: 
Create Date: 2026-03-05 15:39:16.830706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a62775748c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate_to_usd', sa.Float(), nullable=True),
    sa.Column('fx_rate_date', sa.Date(), nullable=True),
    sa.Column('fx_rate_source', sa.String(length=128), nullable=True),
    sa.Column('fx_last_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('firms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_firms_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_firms_slug'), ['slug'], unique=True)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('benchmark_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.String(length=128), nullable=False),
    sa.Column('strategy', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('size_bucket', sa.String(length=128), nullable=True),
    sa.Column('vintage_year', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('quartile', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('upload_batch', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'asset_class', 'strategy', 'region', 'size_bucket', 'vintage_year', 'metric', 'quartile', name='uq_benchmark_points_team_asset_dims_vintage_metric_quartile')
    )
    with op.batch_alter_table('benchmark_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_points_asset_class'), ['asset_class'], unique=False)
        batch_op.create_index('ix_benchmark_points_asset_dims_vintage', ['asset_class', 'strategy', 'region', 'size_bucket', 'vintage_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_points_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_points_size_bucket'), ['size_bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_points_strategy'), ['strategy'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_points_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_points_vintage_year'), ['vintage_year'], unique=False)

    op.create_table('chart_builder_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_chart_builder_templates_team_name')
    )
    with op.batch_alter_table('chart_builder_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chart_builder_templates_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_builder_templates_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_builder_templates_team_id'), ['team_id'], unique=False)

    op.create_table('deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('fund_number', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('geography', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('exit_type', sa.String(length=128), nullable=True),
    sa.Column('lead_partner', sa.String(length=128), nullable=True),
    sa.Column('security_type', sa.String(length=128), nullable=True),
    sa.Column('deal_type', sa.String(length=128), nullable=True),
    sa.Column('entry_channel', sa.String(length=128), nullable=True),
    sa.Column('investment_date', sa.Date(), nullable=True),
    sa.Column('year_invested', sa.Integer(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('equity_invested', sa.Float(), nullable=True),
    sa.Column('ownership_pct', sa.Float(), nullable=True),
    sa.Column('entry_revenue', sa.Float(), nullable=True),
    sa.Column('entry_ebitda', sa.Float(), nullable=True),
    sa.Column('entry_enterprise_value', sa.Float(), nullable=True),
    sa.Column('entry_net_debt', sa.Float(), nullable=True),
    sa.Column('exit_revenue', sa.Float(), nullable=True),
    sa.Column('exit_ebitda', sa.Float(), nullable=True),
    sa.Column('exit_enterprise_value', sa.Float(), nullable=True),
    sa.Column('exit_net_debt', sa.Float(), nullable=True),
    sa.Column('realized_value', sa.Float(), nullable=True),
    sa.Column('unrealized_value', sa.Float(), nullable=True),
    sa.Column('irr', sa.Float(), nullable=True),
    sa.Column('fund_size', sa.Float(), nullable=True),
    sa.Column('net_irr', sa.Float(), nullable=True),
    sa.Column('net_moic', sa.Float(), nullable=True),
    sa.Column('net_dpi', sa.Float(), nullable=True),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('upload_batch', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_team_id'), ['team_id'], unique=False)

    op.create_table('fund_cashflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_number', sa.String(length=50), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('nav_after_event', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('upload_batch', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund_cashflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fund_cashflows_event_date'), ['event_date'], unique=False)
        batch_op.create_index('ix_fund_cashflows_firm_fund_event', ['firm_id', 'fund_number', 'event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_cashflows_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_cashflows_fund_number'), ['fund_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_cashflows_team_id'), ['team_id'], unique=False)

    op.create_table('fund_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_number', sa.String(length=50), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=128), nullable=True),
    sa.Column('region_focus', sa.String(length=128), nullable=True),
    sa.Column('fund_size', sa.Float(), nullable=True),
    sa.Column('first_close_date', sa.Date(), nullable=True),
    sa.Column('final_close_date', sa.Date(), nullable=True),
    sa.Column('manager_name', sa.String(length=255), nullable=True),
    sa.Column('benchmark_peer_group', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('upload_batch', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'firm_id', 'fund_number', name='uq_fund_metadata_team_firm_fund')
    )
    with op.batch_alter_table('fund_metadata', schema=None) as batch_op:
        batch_op.create_index('ix_fund_metadata_firm_fund', ['firm_id', 'fund_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_metadata_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_metadata_fund_number'), ['fund_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_metadata_manager_name'), ['manager_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_metadata_strategy'), ['strategy'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_metadata_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_metadata_vintage_year'), ['vintage_year'], unique=False)

    op.create_table('fund_quarter_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_number', sa.String(length=50), nullable=False),
    sa.Column('quarter_end', sa.Date(), nullable=False),
    sa.Column('committed_capital', sa.Float(), nullable=True),
    sa.Column('paid_in_capital', sa.Float(), nullable=True),
    sa.Column('distributed_capital', sa.Float(), nullable=True),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('unfunded_commitment', sa.Float(), nullable=True),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('upload_batch', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fund_quarter_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fund_quarter_snapshots_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_quarter_snapshots_fund_number'), ['fund_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_quarter_snapshots_quarter_end'), ['quarter_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_fund_quarter_snapshots_team_id'), ['team_id'], unique=False)

    op.create_table('public_market_index_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_code', sa.String(length=64), nullable=False),
    sa.Column('level_date', sa.Date(), nullable=False),
    sa.Column('level', sa.Float(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('upload_batch', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'benchmark_code', 'level_date', name='uq_public_market_index_levels_team_code_date')
    )
    with op.batch_alter_table('public_market_index_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_market_index_levels_benchmark_code'), ['benchmark_code'], unique=False)
        batch_op.create_index('ix_public_market_index_levels_code_date', ['benchmark_code', 'level_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_market_index_levels_level_date'), ['level_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_market_index_levels_team_id'), ['team_id'], unique=False)

    op.create_table('team_firm_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'firm_id', name='uq_team_firm_access_team_firm')
    )
    with op.batch_alter_table('team_firm_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_firm_access_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_firm_access_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_firm_access_team_id'), ['team_id'], unique=False)

    op.create_table('team_invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_invites_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invites_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_invites_token_hash'), ['token_hash'], unique=True)

    op.create_table('team_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_memberships_team_user')
    )
    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_memberships_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('upload_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_report_id', sa.String(length=36), nullable=False),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('upload_batch', sa.String(length=100), nullable=True),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_issues_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_issues_issue_report_id'), ['issue_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_issues_team_id'), ['team_id'], unique=False)

    op.create_table('deal_cashflow_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('upload_batch', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_cashflow_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_cashflow_events_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_cashflow_events_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_cashflow_events_team_id'), ['team_id'], unique=False)

    op.create_table('deal_quarter_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('quarter_end', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('enterprise_value', sa.Float(), nullable=True),
    sa.Column('net_debt', sa.Float(), nullable=True),
    sa.Column('equity_value', sa.Float(), nullable=True),
    sa.Column('valuation_basis', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('upload_batch', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_quarter_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_quarter_snapshots_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_quarter_snapshots_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_quarter_snapshots_quarter_end'), ['quarter_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_quarter_snapshots_team_id'), ['team_id'], unique=False)

    op.create_table('deal_underwrite_baselines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('target_irr', sa.Float(), nullable=True),
    sa.Column('target_moic', sa.Float(), nullable=True),
    sa.Column('target_hold_years', sa.Float(), nullable=True),
    sa.Column('target_exit_multiple', sa.Float(), nullable=True),
    sa.Column('target_revenue_cagr', sa.Float(), nullable=True),
    sa.Column('target_ebitda_cagr', sa.Float(), nullable=True),
    sa.Column('baseline_date', sa.Date(), nullable=True),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('upload_batch', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_underwrite_baselines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_underwrite_baselines_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_underwrite_baselines_firm_id'), ['firm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_underwrite_baselines_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_underwrite_baselines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_underwrite_baselines_team_id'))
        batch_op.drop_index(batch_op.f('ix_deal_underwrite_baselines_firm_id'))
        batch_op.drop_index(batch_op.f('ix_deal_underwrite_baselines_deal_id'))

    op.drop_table('deal_underwrite_baselines')
    with op.batch_alter_table('deal_quarter_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_quarter_snapshots_team_id'))
        batch_op.drop_index(batch_op.f('ix_deal_quarter_snapshots_quarter_end'))
        batch_op.drop_index(batch_op.f('ix_deal_quarter_snapshots_firm_id'))
        batch_op.drop_index(batch_op.f('ix_deal_quarter_snapshots_deal_id'))

    op.drop_table('deal_quarter_snapshots')
    with op.batch_alter_table('deal_cashflow_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_cashflow_events_team_id'))
        batch_op.drop_index(batch_op.f('ix_deal_cashflow_events_firm_id'))
        batch_op.drop_index(batch_op.f('ix_deal_cashflow_events_deal_id'))

    op.drop_table('deal_cashflow_events')
    with op.batch_alter_table('upload_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_issues_team_id'))
        batch_op.drop_index(batch_op.f('ix_upload_issues_issue_report_id'))
        batch_op.drop_index(batch_op.f('ix_upload_issues_firm_id'))

    op.drop_table('upload_issues')
    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_memberships_team_id'))

    op.drop_table('team_memberships')
    with op.batch_alter_table('team_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invites_token_hash'))
        batch_op.drop_index(batch_op.f('ix_team_invites_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_invites_email'))
        batch_op.drop_index(batch_op.f('ix_team_invites_created_by_user_id'))

    op.drop_table('team_invites')
    with op.batch_alter_table('team_firm_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_firm_access_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_firm_access_firm_id'))
        batch_op.drop_index(batch_op.f('ix_team_firm_access_created_by_user_id'))

    op.drop_table('team_firm_access')
    with op.batch_alter_table('public_market_index_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_market_index_levels_team_id'))
        batch_op.drop_index(batch_op.f('ix_public_market_index_levels_level_date'))
        batch_op.drop_index('ix_public_market_index_levels_code_date')
        batch_op.drop_index(batch_op.f('ix_public_market_index_levels_benchmark_code'))

    op.drop_table('public_market_index_levels')
    with op.batch_alter_table('fund_quarter_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_quarter_snapshots_team_id'))
        batch_op.drop_index(batch_op.f('ix_fund_quarter_snapshots_quarter_end'))
        batch_op.drop_index(batch_op.f('ix_fund_quarter_snapshots_fund_number'))
        batch_op.drop_index(batch_op.f('ix_fund_quarter_snapshots_firm_id'))

    op.drop_table('fund_quarter_snapshots')
    with op.batch_alter_table('fund_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_metadata_vintage_year'))
        batch_op.drop_index(batch_op.f('ix_fund_metadata_team_id'))
        batch_op.drop_index(batch_op.f('ix_fund_metadata_strategy'))
        batch_op.drop_index(batch_op.f('ix_fund_metadata_manager_name'))
        batch_op.drop_index('ix_fund_metadata_firm_fund')
        batch_op.drop_index(batch_op.f('ix_fund_metadata_fund_number'))
        batch_op.drop_index(batch_op.f('ix_fund_metadata_firm_id'))

    op.drop_table('fund_metadata')
    with op.batch_alter_table('fund_cashflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fund_cashflows_team_id'))
        batch_op.drop_index(batch_op.f('ix_fund_cashflows_fund_number'))
        batch_op.drop_index(batch_op.f('ix_fund_cashflows_firm_id'))
        batch_op.drop_index('ix_fund_cashflows_firm_fund_event')
        batch_op.drop_index(batch_op.f('ix_fund_cashflows_event_date'))

    op.drop_table('fund_cashflows')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_team_id'))
        batch_op.drop_index(batch_op.f('ix_deals_firm_id'))

    op.drop_table('deals')
    with op.batch_alter_table('chart_builder_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_builder_templates_team_id'))
        batch_op.drop_index(batch_op.f('ix_chart_builder_templates_source'))
        batch_op.drop_index(batch_op.f('ix_chart_builder_templates_created_by_user_id'))

    op.drop_table('chart_builder_templates')
    with op.batch_alter_table('benchmark_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_points_vintage_year'))
        batch_op.drop_index(batch_op.f('ix_benchmark_points_team_id'))
        batch_op.drop_index(batch_op.f('ix_benchmark_points_strategy'))
        batch_op.drop_index(batch_op.f('ix_benchmark_points_size_bucket'))
        batch_op.drop_index(batch_op.f('ix_benchmark_points_region'))
        batch_op.drop_index('ix_benchmark_points_asset_dims_vintage')
        batch_op.drop_index(batch_op.f('ix_benchmark_points_asset_class'))

    op.drop_table('benchmark_points')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_slug'))

    op.drop_table('teams')
    with op.batch_alter_table('firms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_firms_slug'))
        batch_op.drop_index(batch_op.f('ix_firms_name'))

    op.drop_table('firms')
    # ### end Alembic commands ###
